### ISSUE TITLE
 how to solve this error in the training model. I look forward to your answer

### ISSUE THREAD

**Issue by sunsn1997** [ycmin95/VAC_CSLR#16]
Traceback (most recent call last):
  File "main.py", line 211, in <module>
    processor.start()
  File "main.py", line 44, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
  File "/home/linux/data2/sun/VAC_CSLR/seq_scripts.py", line 18, in seq_train
    for batch_idx, data in enumerate(tqdm(loader)):
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/tqdm/std.py", line 1180, in __iter__
    for obj in iterable:
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 530, in __next__
    data = self._next_data()
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1224, in _next_data
    return self._process_data(data)
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/torch/utils/data/dataloader.py", line 1250, in _process_data
    data.reraise()
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/torch/_utils.py", line 457, in reraise
    raise exception
IndexError: Caught IndexError in DataLoader worker process 0.
Original Traceback (most recent call last):
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/torch/utils/data/_utils/worker.py", line 287, in _worker_loop
    data = fetcher.fetch(index)
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in fetch
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/linux/anaconda3/envs/ssn/lib/python3.8/site-packages/torch/utils/data/_utils/fetch.py", line 49, in <listcomp>
    data = [self.dataset[idx] for idx in possibly_batched_index]
  File "/home/linux/data2/sun/VAC_CSLR/dataset/dataloader_video.py", line 47, in __getitem__
    input_data, label = self.normalize(input_data, label)
  File "/home/linux/data2/sun/VAC_CSLR/dataset/dataloader_video.py", line 78, in normalize
    video, label = self.data_aug(video, label, file_id)
  File "/home/linux/data2/sun/VAC_CSLR/utils/video_augmentation.py", line 24, in __call__
    image = t(image)
  File "/home/linux/data2/sun/VAC_CSLR/utils/video_augmentation.py", line 119, in __call__
    if isinstance(clip[0], np.ndarray):
IndexError: list index out of range

**Comment by ycmin95** [comment]
You can check input [here](https://github.com/ycmin95/VAC_CSLR/blob/main/dataset/dataloader_video.py#L62) whether processed images are found.

**Comment by sunsn1997** [comment]
> You can check input [here](https://github.com/ycmin95/VAC_CSLR/blob/main/dataset/dataloader_video.py#L62) whether processed images are found.

Thank you for your answer. I have solved this problem

**Comment by kido1412y2y** [comment]
> > 你可以输入检查   [在这里  ](https://github.com/ycmin95/VAC_CSLR/blob/main/dataset/dataloader_video.py#L62) 是否经过处理的图像。
> 
> 谢谢你的回答。 我已经解决了这个问题

Hello, how did you solve this problem? What changes have been made?

**Comment by Onestringlab** [comment]
Please provide detailed answer to solve this problem.
I don't know how
Thank You
