### ISSUE TITLE
Error when i run the training part main.py

### ISSUE THREAD

**Issue by ethio-artifical** [ycmin95/VAC_CSLR#29]
python main.py --work-dir PATH_TO_SAVE_RESULTS --config F:\code\VAC_CSLR-main1\configs\baseline.yaml --device 'cpu'
.git does not exist in current dir
<__main__.Processor object at 0x0000017E7A49DD50>
[ Sun Mar 12 22:24:52 2023 ] Parameters:
{'work_dir': 'PATH_TO_SAVE_RESULTS', 'config': 'F:\\code\\VAC_CSLR-main1\\configs\\baseline.yaml', 'random_fix': True, 'device': 'cpu', 'phase': 'train', 'save_interval': 5, 'random_seed': 0, 'eval_interval': 1, 'print_log': True, 'log_interval': 50, 'evaluate_tool': 'sclite', 'feeder': 'dataset.dataloader_video.BaseFeeder', 'dataset': 'phoenix14', 'dataset_info': {'dataset_root': './dataset/phoenix2014/phoenix-2014-multisigner', 'dict_path': './preprocess/phoenix2014/gloss_dict.npy', 'evaluation_dir': './evaluation/slr_eval', 'evaluation_prefix': 'phoenix2014-groundtruth'}, 'num_worker': 10, 'feeder_args': {'mode': 'train', 'datatype': 'video', 'num_gloss': -1, 'drop_ratio': 1.0}, 'model': 'slr_network.SLRModel', 'model_args': {'num_classes': 508, 'c2d_type': 'resnet18', 'conv_type': 2, 'use_bn': 1, 'share_classifier': False, 'weight_norm': False}, 'load_weights': None, 'load_checkpoints': None, 'decode_mode': 'beam', 'ignore_weights': [], 'batch_size': 2, 'test_batch_size': 8, 'loss_weights': {'SeqCTC': 1.0}, 'optimizer_args': {'optimizer': 'Adam', 'base_lr': 0.0001, 'step': [20, 35], 'learning_ratio': 1, 'weight_decay': 0.0001, 'start_epoch': 0, 'nesterov': False}, 'num_epoch': 3}

Traceback (most recent call last):
  File "F:\code\VAC_CSLR-main1\main.py", line 220, in <module>
    processor.start()
  File "F:\code\VAC_CSLR-main1\main.py", line 49, in start
    seq_train(self.data_loader['train'], self.model, self.optimizer,
KeyError: 'train'

i got the error when i run python main.py 
can you help me please

these is

**Comment by ycmin95** [comment]
Relevant codes are [here](https://github.com/ycmin95/VAC_CSLR/blob/main/main.py#L169), you can check whether the training date are loaded successfully.
