### ISSUE TITLE
unable to run successfully when I run main.py 

### ISSUE THREAD

**Issue by ethio-artifical** [ycmin95/VAC_CSLR#30]
i got the error when i run main.py because the old version deprecated (pretrained = 'true ') but when I replace     self.conv2d = getattr(models, c2d_type)(weights=ResNet18_Weights.DEFAULT)   i got NameError:....................

Traceback (most recent call last):
  File "F:\code\VAC_CSLR-main1\main.py", line 219, in <module>
    processor = Processor(args)
  File "F:\code\VAC_CSLR-main1\main.py", line 33, in __init__
    self.model, self.optimizer = self.loading()
  File "F:\code\VAC_CSLR-main1\main.py", line 99, in loading
    model = model_class(
  File "F:\code\VAC_CSLR-main1\slr_network.py", line 45, in __init__
    self.conv2d = getattr(models, c2d_type)(weights=ResNet18_Weights.DEFAULT)
NameError: name 'ResNet18_Weights' is not defined

**Comment by ycmin95** [comment]
You can check whether you successfully install ctcdecode.
