### ISSUE TITLE
Run inference for single sample

### ISSUE THREAD

**Issue by RafaelAmauri** [ycmin95/VAC_CSLR#50]
Hello author,

I am trying to run your model to generate the corresponding gloss for a single sample rather than the entire test set. 

I didn't see an option for doing this in the utils/parameters.py file (it appears that inference is only implemented to work on the entire test set rather than a single sample), so I tried modifying the phoenix-2014-multisigner/annotations/manual/test.corpus.csv file to only include one sample and then pre-processed the images in the test folder again to overwrite the .npy representation of the images, but it doesn't work when I do that.

Here's the output stack:

```
rafael@arch >> python main.py --load-weights resnet18_slr_pretrained_distill25.pt --phase test --device 0
Loading model
/home/user/Estudos/VAC-CSLR/venv/lib/python3.8/site-packages/torchvision/models/_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and may be removed in the future, please use 'weights' instead.
  warnings.warn(
/home/rafael/Estudos/VAC-CSLR/venv/lib/python3.8/site-packages/torchvision/models/_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and may be removed in the future. The current behavior is equivalent to passing `weights=ResNet18_Weights.IMAGENET1K_V1`. You can also use `weights=ResNet18_Weights.DEFAULT` to get the most up-to-date weights.
  warnings.warn(msg)
Traceback (most recent call last):
  File "main.py", line 209, in <module>
    processor = Processor(args)
  File "main.py", line 34, in __init__
    self.model, self.optimizer = self.loading()
  File "main.py", line 102, in loading
    self.load_model_weights(model, self.arg.load_weights)
  File "main.py", line 131, in load_model_weights
    model.load_state_dict(weights, strict=True)
  File "/home/rafael/Estudos/VAC-CSLR/venv/lib/python3.8/site-packages/torch/nn/modules/module.py", line 1671, in load_state_dict
    raise RuntimeError('Error(s) in loading state_dict for {}:\n\t{}'.format(
RuntimeError: Error(s) in loading state_dict for SLRModel:
	size mismatch for conv1d.fc.weight: copying a param with shape torch.Size([1296, 1024]) from checkpoint, the shape in current model is torch.Size([7, 1024]).
	size mismatch for conv1d.fc.bias: copying a param with shape torch.Size([1296]) from checkpoint, the shape in current model is torch.Size([7]).
	size mismatch for classifier.weight: copying a param with shape torch.Size([1296, 1024]) from checkpoint, the shape in current model is torch.Size([7, 1024]).
	size mismatch for classifier.bias: copying a param with shape torch.Size([1296]) from checkpoint, the shape in current model is torch.Size([7]).
```

Is there anything else I should do to be able to run the model for a single sample? For this test I deleted most of the contents of test.corpus.csv, all that is left is the header and the first line:

```
id|folder|signer|annotation
01April_2010_Thursday_heute_default-5|01April_2010_Thursday_heute_default-5/1/*.png|Signer04|ABER FREUEN  MORGEN SONNE SELTEN REGEN
```

Any help would be appreciated, especially if there is a way to do this without having to touch the code. If you think there isn't a way to do this without workarounds, I'd appreciate if you'd tell me as well. 

Thanks

**Comment by RafaelAmauri** [comment]
I have figured it out. 

What was happening was that the preprocessing done by the dataset_preprocess.py script was overwriting the gloss_dict.npy file at the very end. Now I don't know exactly what this file does, but the data inside of it is a combination of the dev, test and train CSVs (line 115 of dataset_preprocess.py), and what was happening was that, by deleting most of test.corpus.csv, this would result in my gloss_dict.npy file being less complete too. 

The solution was to first run dataset_preprocess.py on a FULL dev, test and train .corpus.csv files to generate the correct gloss_dict.npy. Then, I modified test.corpus.csv to include only the samples that I want and commented out the last line of dataset_preprocess.py so it doesn't overwrite gloss_dict.npy (If you can't find it, it's `np.save(f"./{args.dataset}/gloss_dict.npy", save_dict)`). Finally, I ran dataset_preprocess.py AGAIN to generate a corresponding test_info.npy file for the samples that I want. 

After that, just run inference normally. This way, inference will run only for the samples that you have selected in the test.corpus.csv file.
